# Default values for hbase.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


images:
  # registry: docker.io
  registry: apecloud-registry.cn-zhangjiakou.cr.aliyuncs.com
  repository: apecloud/hbase
  tag: "2.5.12"
  pullPolicy: IfNotPresent
