# Default values for solr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  solr:
    registry: docker.io
    repository: bitnami/solr
    pullPolicy: IfNotPresent
    tag: 8.11.2

## @param containerPorts.server Solr http server port
##
containerPorts:
  http: 8983
