nameOverride: ""
fullnameOverride: ""

version: "4.3.0"

zoneCount: 1
replicas: 3

cpu: 3
memory: 4
persistence:
  storageClassName: ""
  storages:
    data-file: 30
    data-log: 30
    log: 10
    workdir: 1

hostnetwork: "disabled"
clusterIP: "enabled"
clusterID: "1"

extra:
  disableExporter: false
  terminationPolicy: Delete

# Commit related information
# @param commitInfo - (object) Contains metadata about the last code commit.
commitInfo:
  # @param commitInfo.commitTime - (string) The timestamp of the last code commit, formatted as "YYYY-MM-DD HH:MM:SS".
  # This parameter is used to record the exact time of the most recent code commit.
  commitTime: "2024-12-03 07:20:14"

  # @param commitInfo.commitId - (string) The Git commit hash.
  # This parameter is used to track the specific Git commit identifier associated with the deployment.
  commitId: "1ee46c6a2d4adc7e32d459c637d1568162b1345d"
