apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: rocketmq-reconfiguring
  namespace: demo
spec:
  # Specifies the type of this operation.
  type: Reconfiguring
  # Specifies the name of the Cluster resource that this operation is targeting.
  clusterName: rocketmq-cluster
  # Specifies a component and its configuration updates. This field is deprecated and replaced by `reconfigures`.
  reconfigures:
    # Specifies the name of the Component.
  - componentName: broker
    parameters:
      # Represents the name of the parameter that is to be updated.
      # `channel_max` is a static parameter in rocketmq
    - key: enableMultiDispatch
      # Represents the parameter values that are to be updated.
      # If set to nil, the parameter defined by the Key field will be removed from the configuration file.
      value: "true"