apiVersion: v1
data:
  orc-topology.cnf: |
    [client]
    user=orchestrator
    password=${ORC_TOPOLOGY_PASSWORD}
  orc-backend.cnf: |
    [client]
    user=orchestrator
    password=orchestrator
  orchestrator.conf.json: |-
    {{- .Files.Get "config/orchestrator.tpl" | nindent 4 }}
kind: ConfigMap
metadata:
  name: mysql-orc-config

