image:
  repository: vllm/vllm-openai
  pullPolicy: IfNotPresent
  registry: docker.io
  # Overrides the image tag whose default is the chart appVersion.
  tag: v0.11.2
imageDev:
  # refer: ghcr.io/abetlen/llama-cpp-python:latest
  repository: apecloud/llama-cpp-python
  pullPolicy: IfNotPresent
  # if the value of imageDev.registry is not specified using `--set`, it will be set to the value of 'image.registry' by default
  registry: ""
  # Overrides the image tag whose default is the chart appVersion.
  tag: 20241115-latest
