apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elasticsearch6.configTplName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "elasticsearch.labels" . | nindent 4 }}
  annotations:
  {{ include "kblib.helm.resourcePolicy" . | nindent 4 }}
data:
  elasticsearch.yml: |-
    {{- .Files.Get "configs/elasticsearch-6.yml.tpl" | nindent 4 }}
  log4j2.properties: |-
    {{- .Files.Get "configs/elasticsearch-6-log4j2.properties" | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elasticsearch7.configTplName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "elasticsearch.labels" . | nindent 4 }}
  annotations:
  {{ include "kblib.helm.resourcePolicy" . | nindent 4 }}
data:
  elasticsearch.yml: |-
    {{- .Files.Get "configs/elasticsearch-7.yml.tpl" | nindent 4 }}
  log4j2.properties: |-
    {{- .Files.Get "configs/elasticsearch-7-log4j2.properties" | nindent 4 }}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elasticsearch8.configTplName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "elasticsearch.labels" . | nindent 4 }}
  annotations:
  {{ include "kblib.helm.resourcePolicy" . | nindent 4 }}
data:
  elasticsearch.yml: |-
    {{- .Files.Get "configs/elasticsearch-8.yml.tpl" | nindent 4 }}
  log4j2.properties: |-
    {{- .Files.Get "configs/elasticsearch-8-log4j2.properties" | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kibana6.configTplName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "elasticsearch.labels" . | nindent 4 }}
data:
  kibana.yml: |-
    {{- .Files.Get "configs/kibana-6.yml.tpl" | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kibana7.configTplName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "elasticsearch.labels" . | nindent 4 }}
data:
  kibana.yml: |-
    {{- .Files.Get "configs/kibana-7.yml.tpl" | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kibana8.configTplName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "elasticsearch.labels" . | nindent 4 }}
data:
  kibana.yml: |-
    {{- .Files.Get "configs/kibana-8.yml.tpl" | nindent 4 }}
