# Default values for PostgreSQL (with Patroni HA).
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# if useLegacyCompDef is false ,cluster will be rendered by compDef rather than componentDefRef in cluster definition
useLegacyCompDef: false

## @param version MySQL cluster version
##
version: postgresql-15.7.0

## @param mode postgresql cluster topology mode, standalone, replication
##
mode: standalone

## @param replicas specify cluster replicas
##
replicas: 1

## @param cpu
##
cpu: 0.5

## @param memory, the unit is Gi
##
memory: 0.5

## @param requests.cpu if not set, use cpu
## @param requests.memory, if not set, use memory
##
requests:
#  cpu:
#  memory:

## @param storage size, the unit is Gi
##
storage: 20

## @param monitor sidecar
sidecars:
 - exporter

extra:
  podAntiAffinity: Required
  
etcd:
  proxyEnabled: false
  meta:
    mode: serviceref # optional: incluster, serviceref
    serviceRef:
      namespace: 
      cluster: 
        name: 
        component: 
        service: 
        port: 
        credential:
      serviceDescriptor: postgres-etcd-descriptor # example: postgres-etcd-descriptor