{{- $cc := .Files.Get "config/pg14-config-effect-scope.yaml" | fromYaml }}
apiVersion: apps.kubeblocks.io/v1beta1
kind: ConfigConstraint
metadata:
  name: postgresql16-cc
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  reloadAction:
    tplScriptTrigger:
      sync: true
      scriptConfigMapRef: patroni-reload-script
      namespace: {{ .Release.Namespace }}
    # update patroni master
    targetPodSelector:
      matchLabels:
        "apps.kubeblocks.postgres.patroni/role": "master"

  mergeReloadAndRestart: false

  # ConfigurationSchema that impose restrictions on engine parameter's rule
  parametersSchema:
    # top level pg configuration type
    topLevelKey: PGParameter

    # schemaInJSON: auto generate from cue scripts
    # example: ../../pkg/configuration/testdata/mysql_openapi.json
    cue: |-
      {{- .Files.Get "config/pg16-config-constraint.cue" | nindent 6 }}

  ##  require db instance restart
  ## staticParameters
  {{- if hasKey $cc "staticParameters" }}
  staticParameters:
    {{- $params := get $cc "staticParameters" }}
    {{- range $params }}
    - {{ . }}
    {{- end }}
  {{- end}}

  ## define immutable parameter list, this feature is not currently supported.
  {{- if hasKey $cc "immutableParameters" }}
  immutableParameters:
   {{- $params := get $cc "immutableParameters" }}
   {{- range $params }}
    - {{ . }}
   {{- end }}
  {{- end}}

  # configuration file format
  fileFormatConfig:
    format: properties
