{{- $cc := .Files.Get "config/redis5-config-effect-scope.yaml" | fromYaml }}
apiVersion: apps.kubeblocks.io/v1beta1
kind: ConfigConstraint
metadata:
  name: redis-cluster5-config-constraints
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  # ConfigurationSchema that impose restrictions on engine parameter's rule
  parametersSchema:
    topLevelKey: RedisParameter
    cue: |-
      {{- .Files.Get "config/redis-cluster5-config-constraint.cue" | nindent 6 }}

  ## require db instance restart
  {{- if hasKey $cc "staticParameters" }}
  staticParameters:
    {{- $params := get $cc "staticParameters" }}
    {{- range $params }}
    - {{ . }}
    {{- end }}
  {{- end}}

  ## reload parameters
  ## dynamicParameters
  {{- if hasKey $cc "dynamicParameters" }}
  dynamicParameters:
   {{- $params := get $cc "dynamicParameters" }}
   {{- range $params }}
    - {{ . }}
   {{- end }}
 {{- end}}


  # redis configuration file format
  fileFormatConfig:
    format: redis
