# Default values for rabbitmq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: docker.io
  repository: rabbitmq
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 3.13.2-management

componentServiceVersion:
  rabbitmq: 3.13.2

nameOverride: ""

## Authentication parameters
##
auth:
  ## @param auth.password Password for the "rabbitmq" admin user, leave empty 
  ## for random generated password.
  ##
  password:
  ## @param auth.database Name for a custom database to create
  ##
  database: "admin"

logConfigs:
  running: /data/rabbitmq/logs/rabbitmq.log*

logCollector:
  enabled: false

dataMountPath: /var/lib/rabbitmq


## @param enabledClusterVersions specifies the enabled cluster versions, if not set, all cluster versions are enabled
## and will be rendered, installed. Otherwise, only the specified cluster versions will be rendered and installed.
## Example:
##   --set "enabledClusterVersions={rabbitmq}"
##   --set enabledClusterVersions=''   # this will enable all cluster versions
##   --set enabledClusterVersions={}   # this will disable all cluster versions, the enabledClusterVersions has an empty
##                                     # value and the length is 1
enabledClusterVersions: [ ]

## @param resourceNamePrefix Prefix for all resources name created by this chart, that can avoid name conflict
## if you install multiple releases of this chart.
## If specified, the cluster definition will use it as name.
resourceNamePrefix: "rabbitmq"

# Commit related information
# @param commitInfo - (object) Contains metadata about the last code commit.
commitInfo:
  # @param commitInfo.commitTime - (string) The timestamp of the last code commit, formatted as "YYYY-MM-DD HH:MM:SS".
  # This parameter is used to record the exact time of the most recent code commit.
  commitTime: "2024-12-03 07:20:14"

  # @param commitInfo.commitId - (string) The Git commit hash.
  # This parameter is used to track the specific Git commit identifier associated with the deployment.
  commitId: "1ee46c6a2d4adc7e32d459c637d1568162b1345d"
