apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pulsar4.brokerConfigTplName" . }}
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}
data:
  broker.conf: |-
      {{- .Files.Get "config/4.0.6/broker-config.tpl" | nindent 4 }}
      {{- if eq .Values.cloudProvider "huaweiCloud" }}
    loadBalancerOverrideBrokerNicSpeedGbps=2
      {{- end }}
  client.conf: |-
      {{- .Files.Get "config/4.0.6/pulsar-client-config.tpl" | nindent 4 }}
  pulsar.env : |-
      {{- .Files.Get "config/pulsar-env-optimize.tpl" | nindent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pulsar4.bookiesConfigTplName" . }}
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}
data:
  bookkeeper.conf: |-
    {{- .Files.Get "config/4.0.6/bookies-config.tpl" | nindent 4 }}
  pulsar.env : |-
    {{- .Files.Get "config/pulsar-env.tpl" | nindent 4 }}


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pulsar4.proxyConfigTplName" . }}
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}
data:
  proxy.conf: |-
      {{- .Files.Get "config/4.0.6/proxy-config.tpl" | nindent 4 }}
  pulsar.env : |-
      {{- .Files.Get "config/pulsar-env-optimize.tpl" | nindent 4 }}


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pulsar4.bkRecoveryTplName" . }}
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}
data:
  bookkeeper.conf: |-
    {{- .Files.Get "config/4.0.6/bookies-recovery-config.tpl" | nindent 4 }}
  pulsar.env : |-
    {{- .Files.Get "config/pulsar-env.tpl" | nindent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pulsar4.zookeeperTplName" . }}
  labels:
    {{- include "pulsar.labels" . | nindent 4 }}
data:
  zookeeper.conf: |-
    {{- .Files.Get "config/4.0.6/zookeeper-config.tpl" | nindent 4 }}
  pulsar.env : |-
    {{- .Files.Get "config/zookeeper-env.tpl" | nindent 4 }}
