# Default values for tidb-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @param terminationPolicy define Cluster termination policy. One of DoNotTerminate, Halt, Delete, WipeOut.
##
terminationPolicy: Halt

# @param appVersionOverride 
# if not empty, it will override the default tidb version
# the version must be defined in the clusterversion cr  
appVersionOverride: ""

## @param tolerations define global Tolerations for the cluster all pod's assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## @param topologySpreadConstraints Topology Spread Constraints for pod assignment spread across your cluster among failure-domains. Evaluated as a template
## Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#spread-constraints-for-pods
##
topologyKeys:
  - kubernetes.io/hostname

pd:
  replicas: 3
  resources:
    limits:
      cpu: 2
      memory: 8Gi
    requests:
      cpu: 2
      memory: 8Gi
  persistence:
    data:
      storageClassName: ""
      size: 20Gi
  tolerations: []

tikv:
  replicas: 3
  resources:
    limits:
      cpu: 4
      memory: 16Gi
    requests:
      cpu: 4
      memory: 16Gi
  persistence:
    data:
      storageClassName: ""
      size: 500Gi
  tolerations: []

tidb:
  replicas: 2
  resources:
    limits:
      cpu: 4
      memory: 16Gi
    requests:
      cpu: 4
      memory: 16Gi
  tolerations: []

# The RBAC permission used by cluster component pod, now include event.create
serviceAccount:
  name: ""
