apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentVersion
metadata:
  name: hive
  labels:
    {{- include "hive.labels" . | nindent 4 }}
spec:
  compatibilityRules:
    - releases:
        - v3.1.3
      compDefs:
        - hive-metastore
  releases:
    - name: v3.1.3
      serviceVersion: v3.1.3
      images:
        hadoop-common: "dtweave/hadoop-common:v3.3.4"
        hive-metastore: "{{ .Values.metastore.image.repository }}:{{ .Values.metastore.image.tag }}"