apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "etcd3.configurationTemplate" . }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
  annotations:
    {{- include "etcd.annotations" . | nindent 4 }}

data:
  etcd.conf: |
    {{- .Files.Get "config/etcd.conf.yaml.tpl" | nindent 4 }}
