{{- $cc := .Files.Get "config/config-effect-scope.yaml" | fromYaml }}
apiVersion: apps.kubeblocks.io/v1beta1
kind: ConfigConstraint
metadata:
  name: rabbitmq-env-constraints
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  # rabbitmq configuration file format
  fileFormatConfig:
    format: ini
---

apiVersion: apps.kubeblocks.io/v1beta1
kind: ConfigConstraint
metadata:
  name: rabbitmq-config-constraints
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  # rabbitmq configuration file format
  fileFormatConfig:
    format: ini

  # ConfigurationSchema that impose restrictions on engine parameter's rule
  parametersSchema:
    # top level rabbitmq configuration type
    topLevelKey: RabbitMQParameter

    # schemaInJSON: auto generate from cue scripts
    cue: |-
      {{- .Files.Get "config/config-constraint.cue" | nindent 6 }}

  ## define static parameter list
  {{- if hasKey $cc "staticParameters" }}
  staticParameters:
    {{- $params := get $cc "staticParameters" }}
    {{- range $params }}
    - {{ . }}
    {{- end }}
  {{- end}}