# Default values for hive.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metastore:
  image:
    registry: docker.io
    repository: dtweave/hive-metastore
    tag: "v3.1.3-1.0.0"
    pullPolicy: IfNotPresent