# Default values for wesqlcluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

## Mode of the cluster, optional: standalone, cluster
mode:
  standalone

##### parameters for standalone mode
replicas: 1

persistence:
  enabled: true
  data:
    storageClassName:
    size: 10Gi

##### parameters for cluster mode
proxy:
  enabled: true
  replicas: 1

mixcoord:
  replicas: 1

datanode:
  replicas: 1

indexnode:
  replicas: 1

querynode:
  replicas: 1

storage:
  meta:
    mode: serviceref  # optional: incluster, serviceref
    serviceRef:
      namespace:
      cluster:
        name:
        component:
        service:
        port:
        credential:
      serviceDescriptor:
  log:
    mode: serviceref  # optional: incluster, serviceref
    serviceRef:
      namespace:
      cluster:
        name:
        component:
        service:
        port:
        credential:
      serviceDescriptor:
  object:
    mode: serviceref  # optional: incluster, serviceref
    serviceRef:
      namespace:
      cluster:
        name:
        component:
        service:
        port:
        credential:
      serviceDescriptor:

# Commit related information
# @param commitInfo - (object) Contains metadata about the last code commit.
commitInfo:
  # @param commitInfo.commitTime - (string) The timestamp of the last code commit, formatted as "YYYY-MM-DD HH:MM:SS".
  # This parameter is used to record the exact time of the most recent code commit.
  commitTime: "2024-12-03 07:20:14"

  # @param commitInfo.commitId - (string) The Git commit hash.
  # This parameter is used to track the specific Git commit identifier associated with the deployment.
  commitId: "1ee46c6a2d4adc7e32d459c637d1568162b1345d"
