# Override the name of the chart
nameOverride: ""
# Override the full name of the chart
fullnameOverride: ""

## Clickhouse cluster version
version: 25.9.7

## ClickHouse cluster topology mode defined in ClusterDefinition.Spec.topologies, support standalone and cluster
## - `standalone`: single clickhouse instance
## - `cluster`: clickhouse with ClickHouse Keeper as coordinator
mode: cluster

## Sharding configuration
shards: 2

## Number of ClickHouse replicas per shard to deploy
replicas: 1

## ClickHouse per shard component configurations
cpu: 1
memory: 2

## CPU and memory requests for the ClickHouse shard
requests:
# cpu: ""
# memory: ""

storageClassName: ""
storage: 10
disableExporter: false

## Tolerations for ClickHouse pods assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## ClickHouse Keeper configuration
keeper:
  ## Number of ClickHouse Keeper replicas
  replicas: 1 
  storageClassName: ""
  cpu: 1
  memory: 2
  storage: 10
  tolerations: []

clickhouse:
  initClusterName: "default"

## @param nodePortEnabled if true, the redis will use nodePort as the announce IP
## This option is mutually exclusive with fixedPodIPEnabled, hostNetworkEnabled and loadBalancerEnabled. When all hostNetworkEnabled, fixedPodIPEnabled, nodePortEnabled, loadBalancerEnabled are false, the default announce IP will be a headless service.
nodePortEnabled: false

## Service configurations
service:
  ## ClickHouse service type
  ## Valid options are ExternalName, ClusterIP, NodePort, and LoadBalancer.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: NodePort

## The RBAC permission used by cluster component pod, now include event.create
serviceAccount:
  name: ""

## TLS configuration for ClickHouse cluster
tls:
  enabled: false
  ## UserProvided will automatically generate TLS file by cluster-tls-secrets.yaml
  issuer: UserProvided

extra:
  ## Define Cluster termination policy.
  ## Options: DoNotTerminate, Halt, Delete, WipeOut.
  terminationPolicy: Delete

  ## If true, RBAC resources will be created
  rbacEnabled: false
