etcd:
  endpoints:
  - {{$KB_CLUSTER_NAME}}-etcd-headless.{{$KB_NAMESPACE}}.svc.cluster.local:2379
  rootPath: {{$KB_CLUSTER_NAME}}
messageQueue: rocksmq
minio:
  address: {{$KB_CLUSTER_NAME}}-minio-headless.{{$KB_NAMESPACE}}.svc.cluster.local
  bucketName: {{$KB_CLUSTER_NAME}}
  port: 9000
  accessKeyID: {{$MINIO_ACCESS_KEY}}
  secretAccessKey: {{$MINIO_SECRET_KEY}}
msgChannel:
  chanNamePrefix:
    cluster: {{$KB_CLUSTER_NAME}}
  rocksmq: {}
