image:
  repository: xprobe/xinference
  pullPolicy: IfNotPresent
  # registry: apecloud-registry.cn-zhangjiakou.cr.aliyuncs.com
  registry: docker.io
  # Overrides the image tag whose default is the chart appVersion.
  tag: v0.15.4

# modelDir is the directory where the model is stored in the host.
# If it is not empty, the modelDir will be mounted to /xinference/models in the container.
modelDir: ""

distributed: false