image:
  repository: apecloud/xinference
  pullPolicy: IfNotPresent
  registry: apecloud-registry.cn-zhangjiakou.cr.aliyuncs.com
  # Overrides the image tag whose default is the chart appVersion.
  tag: v1.13.0

# modelDir is the directory where the model is stored in the host.
# If it is not empty, the modelDir will be mounted to /xinference/models in the container.
modelDir: ""

distributed: false
