## set kubernetes cluster domain where minio is running
##
clusterDomain: cluster.local

nameOverride: ""

fullnameOverride: ""

## Set default image, imageTag, and imagePullPolicy. mode is used to indicate the
## Note: from RELEASE.2025-10-15T17-29-55Z, minio changed to source code only distribution,
## so we use the image hosted on coollabsio/minio. If you want to use the old version,
## please set the image.repository to minio/minio.
## Ref: https://github.com/minio/minio?tab=readme-ov-file#source-only-distribution
##
image:
  registry: docker.io
  repository: coollabsio/minio
  pullPolicy: IfNotPresent

## @param versions MinIO versions configuration
## Array of versions with specific image tags and service versions
versions:
  - version: "2024.6.29"
    tag: "RELEASE.2024-06-29T01-20-47Z"
    serviceVersion: "2024.6.29"
  - version: "2025.10.15"
    tag: "RELEASE.2025-10-15T17-29-55Z"
    serviceVersion: "2025.10.15"
    isDefault: true

## Internal port number for MinIO S3 API container
## Change service.port to change external port number
minioAPIPort: "9000"

## Internal port number for MinIO Browser Console container
## Change consoleService.port to change external port number
minioConsolePort: "9001"

## Directory on the MinIO pof
certsPath: "/etc/minio/certs/"
mcConfigPath: "/etc/minio/mc/"

## TLS Settings for MinIO
tls:
  enabled: false
  ## Create a secret with private.key and public.crt files and pass that here. Ref: https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
  certSecret: ""
  publicCrt: public.crt
  privateKey: private.key