# Default values for mongodb-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @param version cluster version
##
version: 6.0.16

## @param topology cluster topology, standalone or replicaset
##
topology: standalone

## @param cpu
##
cpu: 0.5

## @param memory, the unit is Gi
##
memory: 0.5

## @param requests.cpu if not set, use cpuF
## @param requests.memory, if not set, use memory
##
requests:
#  cpu:
#  memory:

## @param storage size, the unit is Gi
##
storage: 20

hostnetwork: "enabled"
