# Default values for tidb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: docker.io
  repository: pingcap
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v7.5.1"
  helper:
    image: "busybox:1.35"
    pullPolicy: IfNotPresent

clusterVersionOverride: ""

clusterDomain: ".cluster.local"
