staticParameters:
 listeners.tcp
 listeners.ssl
 ssl_options.cacertfile
 ssl_options.certfile
 ssl_options.keyfile
 ssl_options.verify
 ssl_options.fail_if_no_peer_cert
 num_acceptors_tcp
 num_acceptors_ssl
 distribution_listener_interface
 distribution_listener_port_range_min
 distribution_listener_port_range_max
 handshake_timeout
 ssl_handshake_timeout
 vm_memory_high_watermark.relative
 vm_memory_high_watermark.absolute
 vm_memory_calculation_strategy
 total_memory_available_override_value
 disk_free_limit.absolute
 queue_leader_locator
 log_file.level
 session_max_per_connection
 link_max_per_session
 channel_max
 channel_operation_timeout
 max_message_size
 heartbeat
 default_vhost
 default_user
 default_pass
 default_user_tags.administrator
 default_permissions.configure
 default_permissions.read
 default_permissions.write
 collect_statistics
 collect_statistics_interval
 management.db_cache_multiplier
 reverse_dns_lookups
 delegate_count
 tcp_listen_options.backlog
 tcp_listen_options.nodelay
 tcp_listen_options.linger.on
 tcp_listen_options.linger.timeout
 tcp_listen_options.exit_on_close
 tcp_listen_options.keepalive
 cluster_partition_handling
 cluster_keepalive_interval
 queue_index_embed_msgs_below
 mnesia_table_loading_retry_timeout
 mnesia_table_loading_retry_limit
 queue_leader_locator
 proxy_protocol
 cluster_name
