apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kblib.clusterName" . }}-server2-accounts
  labels:
    app.kubernetes.io/name: {{ include "kblib.clusterName" . }}
    app.kubernetes.io/component: server2
type: Opaque
stringData:
  # accounts: |
  #   {accountName}:{Password}
  accounts: ""