## @param version StarRocks cluster version
##
version: 3.3.0

## @param replicas specify cluster replicas
##
replicas: 1

## @param cpu
##
cpu: 1

## @param memory, the unit is Gi
##
memory: 1

## @param storage size, the unit is Gi
##
storage: 20

beReplicas: 1
beCPU: 1
beMemory: 1
beStorage: 20

nameOverride: ""

fullnameOverride: ""

clusterVersionOverride: ""

enableStorageServiceRef: false