# HBase Configuration

nameOverride: ""

fullnameOverride: ""

# Replicas for each component
replicas:
  hmaster: 2
  hregionserver: 3

# Resource requirements for each component
resources:
  hmaster:
    requests:
      cpu: "0.1"
      memory: 0.5Gi
    limits:
      cpu: "1"
      memory: 2Gi
  hregionserver:
    requests:
      cpu: "0.1"
      memory: 0.5Gi
    limits:
      cpu: "1"
      memory: 2Gi

# Storage requirements for each component
storage:
  hbaseLog: 2Gi
  hbaseTempData: 10Gi

# Advanced configurations
terminationPolicy: Delete
clusterDef: hbase
topology: hbase-cluster
hadoopCluster:
  name: hadoopcluster
