name: Check Chart PR Review

on:
  pull_request_review:
    paths:
      - "addons/**"
    types: [submitted]


jobs:
  check-helm:
    name: check helm
    if: github.event.review.state == 'approved'
    strategy:
      fail-fast: false
      matrix:
        registry: [ "", "dockerhub", "aliyun" ]
    uses: apecloud/apecloud-cd/.github/workflows/release-charts-check.yml@v0.1.68
    with:
      CHART_DIR: "addons"
      APECD_REF: "v0.1.68"
      SET_REGISTRY: "${{ matrix.registry }}"
    secrets: inherit
