name: Cherry Pick Label Check

on:
  pull_request_target:
    types: [ labeled, unlabeled, synchronize ]
    branches:
      - main
      - release-*

jobs:
  pr-label-check:
    uses: apecloud/apecloud-cd/.github/workflows/pull-request-label-check.yml@v0.1.99
    with:
      CHECK_LABEL: "pick"
      EXTRA_LABEL: "chart-release"
    secrets: inherit
