name: Pull Request Label

on:
  pull_request_target:
    types: [ opened ]
    branches:
      - main
      - release-*

env:
  GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  label-chart-release:
    if: github.event.pull_request.head.repo.full_name != github.repository
    uses: apecloud/apecloud-cd/.github/workflows/pull-request-label.yml@v0.1.61
    with:
      LABEL_NAME: "chart-release"
      LABEL_OPS: "ADD"
      APECD_REF: "v0.1.61"
    secrets: inherit
